namespace Cirreum.Authentication.Configuration;

using Cirreum.AuthenticationProvider.Configuration;

public class EntraAuthenticationSettings
	: AuthenticationProviderSettings<EntraAuthenticationInstanceSettings>;